# Generated by Django 5.1.6 on 2025-02-22 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_user_score_alter_user_gender_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='scored',
        ),
        migrations.RemoveField(
            model_name='course',
            name='users',
        ),
    ]
