# Generated by Django 5.1.6 on 2025-02-22 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_remove_course_scored_remove_course_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.user')),
            ],
        ),
    ]
