# Generated by Django 5.1.6 on 2025-02-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0006_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pic',
            field=models.ImageField(default='static/Quiz/Profile.jpg', upload_to='static/Quiz/profile_pics/'),
        ),
    ]
