# Generated by Django 5.1.6 on 2025-02-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0007_user_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.ImageField(default='Quiz/images/Profile.jpg', upload_to='images/'),
        ),
    ]
