# Generated by Django 5.1.6 on 2025-02-23 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0008_alter_user_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pic',
        ),
    ]
